services:
  - type: web
    name: taskverse-backend
    env: docker
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/taskverse-0.0.1-SNAPSHOT.jar"
    autoDeploy: true
